### ISSUE TITLE
Dydx Error: Create Order: order would put account below collateralization

### ISSUE THREAD

**Issue by shah-smit** [xtf-dapp/xtf-web-app#5]
Current Address has balance of 0.3 Goerli Eth.

Order Being Send:
```json
{
    "market": "ETH-USD",
    "side": "SELL",
    "type": "LIMIT",
    "timeInForce": "GTT",
    "postOnly": false,
    "size": "0.1",
    "price": "100000",
    "limitFee": "0.015",
    "expiration": "2023-01-26T12:38:56.572Z"
}
```

Response:
```
AxiosServerError: 400:  - {
  "errors": [
    {
      "msg": "order would put account below collateralization"
    }
  ]
}
    at axiosRequest (axiosRequest.ts:15:1)
    at async DyDxOrderComponent.tsx:84:1
```

**Comment by shah-smit** [comment]
Account Details:

accountNumber: "0"
createdAt: "2023-01-25T13:38:48.362Z"
equity: "0.000000"
freeCollateral: "0.000000"
id: "21084f4f-190f-54b0-b71e-cc441b620da3"
openPositions: {}
pendingDeposits: "0.000000"
pendingWithdrawals: "0.000000"
positionId: "4452"
quoteBalance: "0.000000"
starkKey: "04f6803a8049bad0d38a2d4db7FAKE238708df2a96e2cb3e2c711a4ccd40"
